# Generated by Django 5.1.5 on 2025-02-12 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('images', models.ImageField(upload_to='')),
                ('likes', models.IntegerField(default=0)),
                ('solution', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Dev_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('images', models.ImageField(upload_to='')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Game_jam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('hosting', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('Game_genre', models.CharField(choices=[('ac', 'Action game'), ('pl', 'Platform game'), ('sh', 'Shooter game'), ('fi', 'Fighting game'), ('st', 'Stealth game'), ('sr', 'Survival game'), ('rh', 'Rhythm game'), ('br', 'Battle Royale game'), ('ad', 'Adventure game'), ('srhr', 'Survival Horror game'), ('tx', 'Text Adventure game'), ('gr', 'Graphic Adventure game'), ('vn', 'Visual Novel game'), ('im', 'Interactive Movie game'), ('pz', 'Puzzle game'), ('ph', 'Physics game'), ('pr', 'Programming game'), ('pzpl', 'Puzzle Platform game'), ('ex', 'Exploration game'), ('hi', 'Hidden Object game'), ('ti', 'Tile Matching game'), ('rp', 'Role Play game'), ('arpg', 'Action Role Play game'), ('crpg', 'Computer Role Play game'), ('mmorpg', 'Massively Multiplayer Online Role Playing games'), ('rg', 'Roguelikes game'), ('trpg', 'Tactical Role Play game'), ('srpg', 'Sandbox Role Play game'), ('drpg', 'Dungeon Role Play game'), ('mr', 'Monster Tamer game'), ('sm', 'Simulation game'), ('cms', 'Construction and Management Simulation game'), ('ls', 'Life Simulation game'), ('vs', 'Vehicle Simulation game'), ('stg', 'Strategy game'), ('4x', '4X game'), ('ar', 'Artillery game'), ('au', 'Auto Battler game'), ('moba', 'Multiplayer Online Battle Arena game'), ('rts', 'Real-time Strategy game'), ('rtt', 'Real-time Tactics game'), ('td', 'Tower Defense game'), ('tbs', 'Turn-based Strategy game'), ('tbt', 'Turn-based Tactics game'), ('wr', 'War game'), ('gs', 'Grand Strategy War game'), ('sp', 'Sports game'), ('rc', 'Racing'), ('cm', 'Competitive'), ('sf', 'Sports-based Fighting game'), ('mmo', 'Massively Multiplayer Online game'), ('bo', 'Board game '), ('cd', 'Card game'), ('ps', 'Parental Simulator game'), ('ca', 'Casino game'), ('dcc', 'Digital Collectible Card game'), ('tr', 'Therapeutic game'), ('gch', 'Gacha game'), ('hr', 'Horror game'), ('id', 'Idle game'), ('pa', 'Party game'), ('pht', 'Photography game'), ('sod', 'Social Deduction game'), ('tv', 'Trivia game'), ('tp', 'Typing game'), ('art', 'Art game'), ('cs', 'Casual game'), ('ed', 'Educational game'), ('exr', 'Exercise game'), ('sd', 'Sandbox game'), ('cr', 'Creative game'), ('op', 'Open World game')], default='ac', max_length=100)),
                ('application_duration', models.DateField()),
                ('monetization', models.BooleanField()),
                ('status', models.CharField(choices=[('o', 'On going'), ('c', 'Completed')], default='o', max_length=1)),
                ('technology', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('images', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('open', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('open', models.BooleanField()),
                ('game_jam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.game_jam')),
            ],
        ),
    ]
