# Generated by Django 5.1.5 on 2025-02-15 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_comment_date_alter_dev_log_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dev_log',
            name='game_jam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.game_jam'),
            preserve_default=False,
        ),
    ]
