# Generated by Django 5.1.5 on 2025-02-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_comment_thread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='images',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
