# Generated by Django 5.1.5 on 2025-02-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_comment_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='images',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
