# Generated by Django 5.1.5 on 2025-02-16 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_comment_user_dev_log_user_game_jam_user_thread_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['-date']},
        ),
    ]
