# Generated by Django 5.1.5 on 2025-02-16 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_thread_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={},
        ),
    ]
