# Generated by Django 5.1.5 on 2025-02-16 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_thread_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dev_log',
            name='images',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='game_jam',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
