# Generated by Django 5.1.5 on 2025-02-16 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_rename_pparticipant_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='game_jam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.game_jam'),
            preserve_default=False,
        ),
    ]
