# Generated by Django 5.1.5 on 2025-02-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_participant_game_jam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='status',
            field=models.CharField(choices=[('w', 'waiting'), ('n', 'not accepted'), ('a', 'accepted')], default='w', max_length=1),
        ),
    ]
