# Generated by Django 5.1.5 on 2025-02-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_alter_participant_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='status',
            field=models.CharField(choices=[('w', 'waiting'), ('d', 'denied'), ('a', 'accepted')], default='w', max_length=1),
        ),
    ]
