# Generated by Django 5.1.5 on 2025-02-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_alter_participant_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='game_jam',
            name='images',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
