# Generated by Django 5.1.5 on 2025-02-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_game_jam_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='images',
            field=models.ImageField(blank=True, upload_to='static/images/uploaded/'),
        ),
        migrations.AlterField(
            model_name='dev_log',
            name='images',
            field=models.ImageField(blank=True, upload_to='static/images/uploaded/'),
        ),
        migrations.AlterField(
            model_name='game_jam',
            name='images',
            field=models.ImageField(blank=True, upload_to='static/images/uploaded/'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='status',
            field=models.CharField(choices=[('w', 'Waiting'), ('d', 'Denied'), ('a', 'Accepted')], default='w', max_length=1),
        ),
        migrations.AlterField(
            model_name='thread',
            name='images',
            field=models.ImageField(blank=True, upload_to='static/images/uploaded/'),
        ),
    ]
