# Generated by Django 5.1.5 on 2025-02-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_alter_comment_images_alter_dev_log_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='images',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='dev_log',
            name='images',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='game_jam',
            name='images',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='thread',
            name='images',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
