# Generated by Django 5.1.5 on 2025-02-19 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_alter_comment_images_alter_dev_log_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='images',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
    ]
